name: build-mosdns

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/build-mosdns.yml'
  schedule:
    - cron: '0 16 * * *'

jobs:
  build-mosdns:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Check out reference branch
        uses: actions/checkout@v3
        with:
          repository: loyalsoldier/v2ray-rules-dat
          ref: release
          path: ref
      - name: Checkout target branch
        uses: actions/checkout@v3
        with:
          ref: mosdns
          path: target
      - name: Clean target branch
        continue-on-error: true
        run: rm target/*
      - name: Rebuild target branch
        run: |
          ./raydata.py ref/geoip.dat -c cn -o target/chinaip.txt geoip
          ./raydata.py ref/geosite.dat -c cn -o target/chinasite.txt geosite --formatter format_mosdns.json
          cd target
          tar -cf mosdns.tar *.txt
          rm *.txt
      - name: Push to target branch
        continue-on-error: true
        run: |
          cd target
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "update $(date +%Y-%m-%d)"
          git push -q
