name: build-sha

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/build-sha.yml'
  schedule:
    - cron: '0 16 * * *'

jobs:
  build-sha:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Check out reference branch
        uses: actions/checkout@v3
        with:
          repository: gaoyifan/china-operator-ip
          ref: ip-lists
          path: ref
      - name: Checkout target branch
        uses: actions/checkout@v3
        with:
          ref: sha
          path: target
      - name: Clean target branch
        continue-on-error: true
        run: rm target/*
      - name: Rebuild target branch
        run: |
          ./netgen.py ref/china.txt -o target/china.sh -p 'ip route add ' -s $' dev eth0 via 10.11.0.1 || true\n'
          ./netgen.py ref/china6.txt -o target/china6.sh -p 'ip route add ' -s $' dev eth0 via fe80::6a77:24ff:fed6:809d || true\n'
          ./netgen.py ref/china.txt -o target/rm-china.sh -p 'ip route del ' -s $' dev eth0 via 10.11.0.1 || true\n'
          ./netgen.py ref/china6.txt -o target/rm-china6.sh -p 'ip route del ' -s $' dev eth0 via fe80::6a77:24ff:fed6:809d || true\n'
          cd target
          chmod +x *.sh
          tar -cf sha.tar *.sh
          rm *.sh
      - name: Push to target branch
        continue-on-error: true
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "update $(date +%Y-%m-%d)"
          git push -q
