name: checkout-better-cf-ip

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/checkout-better-cf-ip.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  checkout-better-cf-ip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/github-script@v7
        id: latest_tag
        with:
          #result-encoding: string
          retries: 3
          script: |
            const ret = await github.rest.repos.getLatestRelease({
              owner: "XIU2",
              repo: "CloudflareSpeedTest"
            })
            console.log(ret)
            return ret.data.tag_name
      - name: confirm release tag
        run: |
          echo ${{ steps.latest_tag.outputs.result }}
